apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbenga-and-sons-deployment
  labels:
    app: gbenga-and-sons
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbenga-and-sons
  template:
    metadata:
      labels:
        app: gbenga-and-sons
    spec:
      containers:
      - name: gbenga-and-sons-container
        image: kelomo2502/gbenga-and-sons:v1 # Replace with your Docker Hub image
        ports:
        - containerPort: 80 # Update with the port your app listens on
