apiVersion: v1
kind: Service
metadata:
  name: gbenga-and-sons-service
spec:
  selector:
    app: gbenga-and-sons
  ports:
  - protocol: TCP
    port: 80       # Exposed port
    targetPort: 80 # The port your app listens on
  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: gbenga-and-sons-service
spec:
  selector:
    app: gbenga-and-sons
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 80 # Container port
  type: ClusterIP # Default type for internal services
